//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLUnitPrice
    {
        public int POLUnitPriceId { get; set; }
        public Nullable<decimal> CNGUnitPrice { get; set; }
        public Nullable<decimal> DieselUnitPrice { get; set; }
        public Nullable<decimal> EngineOilUnitPrice { get; set; }
        public Nullable<decimal> PowerOilUnitPrice { get; set; }
        public Nullable<decimal> GearOilUnitPrice { get; set; }
        public Nullable<decimal> GreaseUnitPrice { get; set; }
        public string Status { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Notes { get; set; }
    }
}
