//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandip.DAL
{
    using System;
    
    public partial class prGetPartsDetails_Result1
    {
        public int PartsId { get; set; }
        public string PartsCode { get; set; }
        public string PartsName { get; set; }
        public string PartsDescription { get; set; }
        public string PartsSize { get; set; }
        public string Brand { get; set; }
        public Nullable<int> VendorId { get; set; }
        public Nullable<int> CarTypeId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public string Units { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string RackNo { get; set; }
        public string CarTypeName { get; set; }
        public Nullable<decimal> Balance { get; set; }
    }
}
