//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandip.DAL
{
    using System;
    
    public partial class prGetDailyPOLLog_Result1
    {
        public int POLId { get; set; }
        public Nullable<int> CarId { get; set; }
        public string RegistrationNo { get; set; }
        public string CheckInDate { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string DriverName { get; set; }
        public string DriverNameBangla { get; set; }
        public Nullable<int> IssuedById { get; set; }
        public string IssuedByName { get; set; }
        public string IssuedByNameBangla { get; set; }
        public decimal CNG { get; set; }
        public Nullable<decimal> Diesel { get; set; }
        public Nullable<decimal> EngineOil { get; set; }
        public Nullable<decimal> PowerOil { get; set; }
        public Nullable<decimal> GearOil { get; set; }
        public Nullable<decimal> Grease { get; set; }
        public string Status { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> AprrovedBy { get; set; }
        public string ApprovedByName { get; set; }
        public Nullable<int> POLAmountId { get; set; }
        public Nullable<decimal> CNGCost { get; set; }
        public Nullable<decimal> DieselCost { get; set; }
        public Nullable<decimal> EngineOilCost { get; set; }
        public Nullable<decimal> PowerOilCost { get; set; }
        public Nullable<decimal> GearOilCost { get; set; }
        public Nullable<decimal> GreaseCost { get; set; }
    }
}
