//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInfo
    {
        public int StoreInfoId { get; set; }
        public Nullable<int> PartsId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<decimal> QuantityIn { get; set; }
        public Nullable<decimal> QuantityOut { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string PurchaseRef { get; set; }
        public string RequisitionRef { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> JobIdRef { get; set; }
        public Nullable<int> VendorId { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual PartsDetail PartsDetail { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
