//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sandip.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailyCarHistory
    {
        public int CarLogId { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> RootId { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public string CheckInTime { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public string CheckOutTime { get; set; }
        public Nullable<decimal> TripNo { get; set; }
        public Nullable<decimal> TotalDistance { get; set; }
        public string CheckInBy { get; set; }
        public string CheckOutBy { get; set; }
        public Nullable<bool> IsUnwantedReturn { get; set; }
        public string ReasonForReturn { get; set; }
        public string Status { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Creation { get; set; }
        public Nullable<System.DateTime> Update { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public string RouteStartPoint { get; set; }
        public Nullable<decimal> ExceptioalAmount { get; set; }
        public string TripType { get; set; }
        public Nullable<decimal> OnRouteIncome { get; set; }
        public Nullable<decimal> DifferentRouteIncome { get; set; }
        public Nullable<int> DifferentRouteDistance { get; set; }
        public string AdditionalIncomeType { get; set; }
        public Nullable<decimal> TotalIncome { get; set; }
        public Nullable<bool> IsUnOfficialDay { get; set; }
    }
}
