export class COA{
    COAId:number;
    AccountCode:string;
    IsGroup:boolean;
    ParentID:number;
    AccountName:string;
    AccountDescription:string;
    AccountType:string;
    TrackVendor:boolean;
    TrackBank:boolean;
    TrackCustomer:boolean;
    TrackBill:boolean;
    TrackEmployee:boolean;
    TrackDemand:boolean;
    TrackAssetItem:boolean;
    CompanyId:number;
    CreatedBy:number;
    CreatedByName:number;
    Status:string;
}